### PR TITLE
update documentation link to github wiki in readme

### PR DESCRIPTION
**Pull request by maf-embraceit**

### CODE REVIEW

**Comment by emicha** [comment]
@maf-embraceit could we also change the text of the intro to:
```
AltaPay, headquartered in Denmark, is an internationally focused fintech company within payments with the mission to make payments less complicated. We help our merchants grow and expand their business across payment channels by offering a fully integrated seamless omni-channel experience for online, mobile and instore payments, creating transparency and reducing the need for manual tasks with one centralized payment platform.
AltaPay’s platform automizes, simplifies, and protects the transaction flow for shop owners and global retail and e-commerce companies, supporting and integrating smoothly into the major ERP systems. AltaPay performs as a Payment Service Provider operating under The Payment Card Industry Data Security Standard (PCI DSS).
```

**Comment by maf-embraceit** [comment]
sure, done

**Comment by maf-embraceit** [comment]
@emicha sure, done

**Review by shahbaz-mehar — COMMENTED** [review]
Changes have been reviewed.

**Review by emicha — APPROVED** [review]

**Pull request merged**
